twig:
    default_path: '%kernel.project_dir%/templates'
    globals: 
            images: "/img/post/"
            profile_image: "/img/profile/"

when@test:
    twig:
        strict_variables: true
        form_themes: ['bootstrap_5_layout.html.twig']